server:
  port: 8080
spring:
  application:
    name: inbound-data-processor
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cold
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db\changelog\db.changelog-master.yaml
inbound: C:\\Users\\panka\\OneDrive\\Desktop\\data\\inbound\\
archive: C:\\Users\\panka\\OneDrive\\Desktop\\data\\archive\\
stopFile: C:\\Users\\panka\\OneDrive\\Desktop\\data\\stop
errorPath: C:\\Users\\panka\\OneDrive\\Desktop\\data\\error\\
process:
  files: all
extension:
  file:
    trig: .trig
    lock: .lock
    error: .err
retry: 10