server:
  port: 8080
spring:
  application:
    name: inbound-data-processor
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mysqldb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
inbound: C:\\Users\\HP\\Desktop\\cold-storage\\data\\inbound\\
archive: C:\\Users\\HP\\Desktop\\cold-storage\\data\\archive\\
stopFile: C:\\sers\\HP\\Desktop\\cold-storage\\data\\stop.1
errorPath:  C:\\Users\\HP\\Desktop\\cold-storage\\data\\error\\
process:
  files: all
extension:
  file:
    trig: .trig
    lock: .lock
    error: .err
retry: 10